import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { analyzeWebsiteWithGemini } from '@/lib/gemini';
import { analyzeWebsiteWithGroq } from '@/lib/groq';

const DB_FILE_PATH = path.join(process.cwd(), 'data', 'db.json');

function getDbData() {
  try {
    if (fs.existsSync(DB_FILE_PATH)) {
      const raw = fs.readFileSync(DB_FILE_PATH, 'utf8');
      return JSON.parse(raw);
    }
  } catch (e) {
    console.error("Error reading db.json:", e);
  }
  return { templates: [] };
}

function saveDbData(data) {
  try {
    const dir = path.dirname(DB_FILE_PATH);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(DB_FILE_PATH, JSON.stringify(data, null, 2), 'utf8');
  } catch (e) {
    console.error("Error writing db.json:", e);
  }
}

export async function POST(req) {
  try {
    const { url, apiKey } = await req.json();

    if (!url) {
      return NextResponse.json({ error: 'URL is required' }, { status: 400 });
    }

    // Normalize URL
    let targetUrl = url.trim();
    if (!targetUrl.startsWith('http://') && !targetUrl.startsWith('https://')) {
      targetUrl = 'https://' + targetUrl;
    }
    const cleanNormUrl = targetUrl.replace(/\/$/, '').toLowerCase();

    // 1. CHECK DISK DATABASE CACHE FIRST (data/db.json)
    const db = getDbData();
    const cachedEntry = db.templates.find(
      (t) => t.url && t.url.replace(/\/$/, '').toLowerCase() === cleanNormUrl
    );

    if (cachedEntry) {
      console.log(`Returning analyzed design from disk database (data/db.json) for: ${cleanNormUrl}`);
      return NextResponse.json({ success: true, template: cachedEntry, cached: true });
    }

    // Server-side HTML fetch to extract context
    let pageTitle = '';
    let pageText = '';
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 6000);
      const res = await fetch(targetUrl, {
        signal: controller.signal,
        headers: {
          'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
        }
      });
      clearTimeout(timeoutId);

      if (res.ok) {
        const html = await res.text();
        const titleMatch = html.match(/<title[^>]*>([^<]+)<\/title>/i);
        if (titleMatch) pageTitle = titleMatch[1].trim();

        pageText = html.replace(/<script\b[^<]*>([\s\S]*?)<\/script>/gi, '')
                       .replace(/<style\b[^<]*>([\s\S]*?)<\/style>/gi, '')
                       .replace(/<[^>]+>/g, ' ')
                       .replace(/\s+/g, ' ')
                       .trim();
      }
    } catch (fetchErr) {
      console.warn("Could not pre-fetch URL server side:", fetchErr.message);
    }

    let result;
    const groqKey = apiKey || process.env.GROQ_API_KEY;
    const geminiKey = apiKey || process.env.GEMINI_API_KEY;

    // Automated Fallback Execution Chain: Groq -> Gemini -> Synthesis Engine
    if (groqKey) {
      try {
        console.log("Attempting website analysis with Groq AI (Llama 3.3 70B)...");
        result = await analyzeWebsiteWithGroq({ url: targetUrl, apiKey: groqKey, pageText, title: pageTitle });
      } catch (groqErr) {
        console.warn("Groq API failed or unavailable, falling back to Gemini API:", groqErr.message);
        if (geminiKey) {
          try {
            result = await analyzeWebsiteWithGemini({ url: targetUrl, apiKey: geminiKey, pageText, title: pageTitle });
          } catch (geminiErr) {
            console.warn("Gemini API also failed, using design synthesis engine:", geminiErr.message);
          }
        }
      }
    } else if (geminiKey) {
      try {
        console.log("Attempting website analysis with Gemini API (Gemini 2.0)...");
        result = await analyzeWebsiteWithGemini({ url: targetUrl, apiKey: geminiKey, pageText, title: pageTitle });
      } catch (geminiErr) {
        console.warn("Gemini API failed, using design synthesis engine:", geminiErr.message);
      }
    }

    // Fallback synthesis if no keys or all APIs fail
    if (!result) {
      console.log("Using design synthesis fallback engine");
      const hostname = new URL(targetUrl).hostname.replace('www.', '');
      const cleanName = hostname.split('.')[0];
      const capitalized = cleanName.charAt(0).toUpperCase() + cleanName.slice(1);

      result = {
        id: `custom-${Date.now()}`,
        title: `${capitalized} Design System — Animated Interface`,
        url: targetUrl,
        category: "SaaS",
        style: "Animated High-Contrast Dark",
        description: `Autogenerated design profile for ${hostname}. Features preloader transitions, smooth scroll animations, high-contrast color scheme, and responsive micro-interactions.`,
        colors: [
          { hex: "#0c0e14", name: "Onyx Canvas", role: "Background" },
          { hex: "#161a24", name: "Elevated Surface", role: "Cards & Modals" },
          { hex: "#6366f1", name: "Indigo Accent", role: "Primary Accent" },
          { hex: "#94a3b8", name: "Slate Muted", role: "Secondary Text" },
          { hex: "#f8fafc", name: "Crystal White", role: "Primary Text" }
        ],
        typography: {
          primary: "Inter / Plus Jakarta Sans",
          secondary: "JetBrains Mono",
          notes: "Responsive display typography with subtle letter spacing adjustments."
        },
        vibe: ["Animated Motion", "Modern Contrast", "Responsive UI", "Smooth Preloader"],
        masterPrompt: `Create a modern responsive website inspired by ${hostname}.\nKEY DESIGN SPECIFICATIONS:\n- Palette: Background #0c0e14, Cards #161a24 with 1px border rgba(255,255,255,0.1), Primary Accent #6366f1, Text #f8fafc, Muted text #94a3b8.\n- Motion & Animations: Preloader intro screen (2.5s fade out), scroll-driven reveal transitions for cards, smooth hover scale physics (scale 1.03).\n- Typography: Inter sans-serif for main titles and body, JetBrains Mono for code or metrics.\n- Components:\n  1. Glassmorphism header navbar with logo and smooth blur backdrop.\n  2. High-impact hero section with primary action button and secondary outline button.\n  3. Responsive 3-column feature grid with hover scale and glow outline.\n  4. Footer with categorized link columns and newsletter signup form.`,
        tailwindConfig: `// tailwind.config.js\nmodule.exports = {\n  theme: {\n    extend: {\n      colors: {\n        bgMain: '#0c0e14',\n        bgCard: '#161a24',\n        accent: '#6366f1',\n      }\n    }\n  }\n}`,
        cssVariables: `:root {\n  --bg-main: #0c0e14;\n  --bg-card: #161a24;\n  --accent: #6366f1;\n  --text-main: #f8fafc;\n}`
      };
    }

    // High-Resolution Microlink Screenshot API
    const liveScreenshotUrl = `https://api.microlink.io/?url=${encodeURIComponent(targetUrl)}&screenshot=true&embed=screenshot.url`;

    const finalTemplate = {
      id: result.id || `custom-${Date.now()}`,
      title: result.title || `${url} Interface`,
      url: targetUrl,
      category: result.category || 'SaaS',
      style: result.style || 'Modern Web',
      description: result.description || `Design breakdown of ${url}`,
      image: liveScreenshotUrl,
      colors: result.colors || [
        { hex: "#0f172a", name: "Slate Dark", role: "Background" },
        { hex: "#38bdf8", name: "Sky Accent", role: "Primary Accent" },
        { hex: "#f8fafc", name: "Pure Light", role: "Primary Text" }
      ],
      typography: result.typography || { primary: "Inter", secondary: "Monospace", notes: "Clean hierarchy" },
      vibe: result.vibe || ["Animated", "Modern", "Responsive"],
      masterPrompt: result.masterPrompt || `Recreate design for ${url}`,
      tailwindConfig: result.tailwindConfig || `// tailwind config`,
      cssVariables: result.cssVariables || `:root {}`,
      createdAt: new Date().toISOString(),
      isFeatured: true
    };

    // SAVE NEW ANALYSIS PERMANENTLY TO DISK DATABASE (data/db.json)
    const updatedDb = getDbData();
    const filteredDbTemplates = updatedDb.templates.filter(
      (t) => t.url && t.url.replace(/\/$/, '').toLowerCase() !== cleanNormUrl
    );
    updatedDb.templates = [finalTemplate, ...filteredDbTemplates];
    saveDbData(updatedDb);

    return NextResponse.json({ success: true, template: finalTemplate, cached: false });

  } catch (error) {
    console.error("API /api/analyze Error:", error);
    return NextResponse.json(
      { error: error.message || 'Failed to analyze website URL' },
      { status: 500 }
    );
  }
}
